folder: "/pasteur/homes/azhukova/projects/PASTML/cytopast/examples/HIV1C"
data_dir: 'data'
fasta_la: 'HIV1_ALL_2017_pol_DNA.fasta'
fasta_phylotype: 'HIV-1C.fasta'
data_phylotype: 'HIV-1C.tab'

lsd: "/pasteur/homes/azhukova/apps/lsd-0.3beta-master/src/lsd"
tnt: "/pasteur/homes/azhukova/apps/tnt/tnt"
fasttree: "module load FastTree/2.1.8; FastTree"
phyml: "module load phyml/3.1; phyml"
raxml: "module load RAxML/8.2.8; raxmlHPC-PTHREADS"
mafft: "module load mafft/7.397; mafft"

src: '. /etc/profile.d/pasteur_modules.sh'
py_config: 'module load conda/3.19.0; source /local/gensoft2/exe/conda/3.19.0/conda/bin/activate py3'