folder: ".."
data_dir: 'data'
fasta_la: 'HIV1_ALL_2017_pol_DNA.fasta'
fasta_phylotype: 'HIV-1C.fasta'
data_phylotype: 'HIV-1C.tab'

lsd: lsd
fasttree: fasttree
raxml: raxmlHPC-PTHREADS
phyml: phyml
tnt: tnt
mafft: mafft
src: echo ""
py_config: "source activate cytopast"
