folder: "/pasteur/homes/azhukova/projects/PASTML/cytopast/examples/HIV1C"
data_dir: 'data'
fasta_la: 'HIV1_ALL_2017_pol_DNA.fasta'
fasta_phylotype: 'HIV-1C.fasta'
data_phylotype: 'HIV-1C.tab'

lsd: lsd
fasttree: fasttree
phyml: phyml
tnt: tnt
mafft: mafft
src: ". /etc/profile.d/pasteur_modules.sh"
py_config: "module load gmp/6.0.0; module load conda/3.19.0; source /local/gensoft2/exe/conda/3.19.0/conda/bin/activate py3"